version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: cartrader
      POSTGRES_DB: car_trader
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    ports:
      - "5432:5432"  

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
    driver: local

#docker-compose up --build
